language: node_js
node_js:
  - 0.6
notifications:
  email:
    recipients:
      - brianloveswords@gmail.com
before_script:
  - cp lib/environments/local-dist.js lib/environments/local.js
  - mysql -e 'create database test_openbadges;'
  - mysql -uroot -e "grant all on test_openbadges.* to 'badgemaker'@'localhost' identified by 'secret'"
