language: node_js
node_js:
  - 0.6
notifications:
  email:
    recipients:
      - brianloveswords@gmail.com
before_script:
  - ln -s lib/environments/local-dist.js lib/environments/local.js
  - mysql -e 'create database openbadges;'
  - mysql -e "grant all on openbadges.* to user 'badgemaker'@'localhost' identified by 'secret'"
